# fly.toml app configuration file generated for food-drive on 2023-10-12T07:38:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "food-drive"
primary_region = "ams"

[build]
  builder = "heroku/buildpacks:20"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = 8080
  PLT_SERVER_HOSTNAME = "0.0.0.0"
  PLT_SERVER_LOGGER_LEVEL = "info"
  DATABASE_URL = "postgresql://foodbank@127.0.0.1:5432/fooddrive"
